#!/usr/bin/env node
/**
 * generate-pixel.mjs — writes public/pixel.js with the Meta Pixel ID from env.
 * If VITE_META_PIXEL_ID is unset, writes a no-op stub (safe).
 * Runs in the build pipeline before vite build (public/ is copied as-is).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const pid = process.env.VITE_META_PIXEL_ID || '';

const stub = `// Meta Pixel loader — generated by scripts/generate-pixel.mjs
(function () {
  var pid = ${JSON.stringify(pid)};
  if (!pid) return; // no pixel configured → no-op
  !function (f, b, e, v, n, t, s) {
    if (f.fbq) return; n = f.fbq = function () {
      n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments);
    };
    if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
    n.queue = []; t = b.createElement(e); t.async = !0;
    t.src = v; s = b.getElementsByTagName(e)[0]; s.parentNode.insertBefore(t, s);
  }(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', pid);
  fbq('track', 'PageView');
})();
`;

mkdirSync(resolve(root, 'public'), { recursive: true });
writeFileSync(resolve(root, 'public/pixel.js'), stub);
console.log(pid ? `✅ Meta Pixel ${pid} written to public/pixel.js` : '⚠️  No VITE_META_PIXEL_ID set — wrote no-op pixel.js');
